config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :charges

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users, only: [:edit, :update, :show ]
  

  devise_for :users, :controllers => {:registrations => "registrations"}

  root 'pages#landing_page'
  
  get 'landing_page', to: 'pages#landing_page'

  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'

  get 'pricing', to: 'pages#pricing'

  get 'features', to: 'pages#features'

  post 'get_started_email', to: 'pages#get_started_email'

  get 'get_started', to: 'pages#get_started'

  get 'shop', to: 'pages#shop'

  post 'charge', to: 'charges#create'

  get 'demo', to: 'pages#demo'

  get 'sign_up', to: 'registrations#create'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #guest user (not logged in)
    can :manage, User, id: user.id
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
        if user.is_admin?
            can :access, :rails_admin
            can :dashboard
        end
    end
    
  end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true
	validates :amount, presence: true
	validates :cost, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         def full_name 
        "#{first_name} #{last_name}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
skip_before_filter  :verify_authenticity_token, :authenticate_user!
	def new
	end

	def create
		#amount in cents
		

		customer = Stripe::Customer.create(
			:email => 'example@stripe.com',
			:card => params[:stripeToken],
			#:first_name => "FirstName",
			#:last_name => "LastName",
			#:billing_address => "BillingAddress",
			#:billing_city => "City",
			#:billing_state => "State",
			#:billing_zip => "zip",
			#:shipping_address => "BillingAddress",
			#:shipping_city => "City",
			#:shipping_state => "State",
			#:shipping_zip => "zip"


			)

		charge = Stripe::Charge.create(
			:customer => customer.id,
			:amount => params[:amount],
			:description => 'Rails Stripe customer',
			:currency => 'usd'
			)

	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to charges_path
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  def landing_page
  end

  def contact
  end

  def about
  end

  def pricing
  end

  def features
  end

  def get_started_email
    name = params['name']
    store_name = params['store_name']
    phone_number = params['phone_number']
    email = params['email_address']

    ContactMailer.get_started_email(:from => email, :subject => name + " from " + store_name + " wants to get started", :body => phone_number).deliver
    redirect_to '/get_started'
  end

  def shop
    @products = Product.all
  end

  def get_started

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :amount, :manufacture_part, :tms_id, :quick_overview, :read_more, :description, :image_url, :cost)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	
	def sign_up(resource_name, resource)
		resource.update_attribute(:is_admin, true) 
		if resource_name.to_s.camelcase.constantize.count ==1
		super
		end
	end
end

app/controllers/users_controller.rb
class UsersController <ApplicationController

	before_filter :authenticate_user!
	load_and_authorize_resource 
	 
	 def show
	 	
	 end

	 def edit
	 	
	 end

	 def update
	 	@user.update_attributes(user_params)
	 	
	 end
	
	


	 private

	 def user_params
	 	require(:user)
	 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= product.amount %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do |c|%>
  <div>
    <%= c.label :amount %>
   <%= c.hidden_field_tag "amount", @product.amount %>
     
  </div>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="<%= product.name %>"
          data-amount="<% product.amount%> "> </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">

  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">

 	 <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Electronic Payment Solutions, credit card processing, point of sale solutions hardware and software and other tools to help businesses manage payments.">
    <meta name="author" content="Tri-State Merchant Services Inc.">
    <%= favicon_link_tag '/favicon.ico' %>
   
    
</head>
<body data-spy="scroll" data-target=".navbar">
 
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <div class="navbar-brand"><%= link_to image_tag('logo.png'), '/landing_page'  %>
         </div>
        </div>
<div class="navbar-collapse collapse">
          <div class="navbar-right">
            <div class="row">
             <p>Questions? Call us at 1-888-952-3600 or <a href="mailto:sales@tmsmerchant.com?subject=Please Contact me about VMC">contact us.</a>

              <a type="submit" class="btn btn-gold" href="/demo">Sign up for a demo</a> 
            </div>
          <div class="row">
           <ul class="list-inline rightnav">
            
            <li><%= link_to 'Features', '/features' %></li>
            <li><%= link_to 'Pricing', '/pricing' %></li>
            <li><%= link_to 'Get Started', '/get_started' %></li>
            &nbsp; &nbsp; &nbsp; &nbsp;
            <% if user_signed_in? %>
            <li class="sign_in"><%= link_to 'log out', destroy_user_session_path, method: :delete %></li>
             <li class="sign_in"><%= link_to "Edit", edit_user_path(current_user) %></li>
            <% else %>
            <li class="sign_in"><%= link_to "Sign Up", new_user_registration_path %></li>
            <li class="sign_in"><%= link_to "Sign In", new_user_session_path %></li>
           
           
            <%end%>
          	</ul>
        	</div>
          </div>
        </div><!--/.navbar-collapse -->
      </div>
    </div> <!--end nav bar-->


<%= yield %>

<hr>
 <div class="container footer">
         <footer>
          <ul class="list-inline">
            
            <li><%= link_to 'Home', '/landing_page' %></li>
            <li><%= link_to 'Features', '/features' %></li>
            <li><%= link_to 'Pricing', '/pricing' %></li>
             <li><%= link_to 'Get Started', '/get_started' %></li>
            <li><%= link_to 'About', '/about' %></li>
            <li><%= link_to 'Contact', '/contact' %></li>
             <li><%= link_to 'Merchants', '/users/sign_up' %></li>
             <li><%= link_to 'Shop', '/shop' %></li>
         

           
          </ul>
          <p class="text-right"><small>&copy; Tri-State Merchant Services, Inc. 2014</small></p>
      </footer>
      </div>

    <script type="text/javascript">$.stellar(); </script>
     
  <script type="text/javascript">
  var $root = $('html, body');
    $('.nav a').click(function() {
        var href = $.attr(this, 'href');
        $root.animate({
            scrollTop: $(href).offset().top
        }, 500, function () {
            window.location.hash = href;
        });
        return false;
    });
    </script>
    
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>


  
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/_form_get_started.html.erb
<form roll="form" class="form-inline" method="post" action="get_started_email">
    <div class="form-group form-block">
        <label for="name"></label> <input type="text" id="name" name="name"placeholder="Name"><br>
        <label for="storename"></label> <input type="text" id="storename" name="store_name" placeholder="Store Name"><br>
    </div>
    <div class="form-group">
        <label for="phonenumber"></label> <input type="tel" id="phonenumber" name="phone_number" placeholder="Phone Number"><br>
        <label for="emailaddress"></label> <input type="text" id="storename" name="email_address" placeholder="Email Address"><br>
    </div>
         
    <button type="submit" class="btn btn-blue btn-block" >Get Started</button>
 </form> 

app/views/pages/about.html.erb
<div class ="container about_us">
	<div class="row">
		<div class="col-md-6">
			<h4> Tri-State Merchant Services, Inc.</h4>
			<p>Backed by Vantiv/NPC, one of the top Merchant Acquirers in the US, Tri-State Merchant Services Inc. is proud to offer affordable management and payment solutions along with personalized customer service.  We understand what it means to be a small to midsize business and how important it is to take advantage of available technology to compete in today’s market.</p>  

			<p>Since 1995, Tri-State Merchant Services had been committed to providing superior service in a continued effort to exceed our merchant’s expectations and requirements. Our team strives to create the value-added services necessary to maintain long-term partnerships with our clients.</p>

			<p>Let us help your business grow.  Our world-class customer service is available 24 x 7 and the personal attention from our sales office is unbeatable.  We encourage our merchants to reach out to us with anything from basic questions to implementing an advanced payment solution strategy.</p>

			<p>We look forward to hearing from you and working together to streamline your business solutions.</p>

		</div>
	</div>

</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/demo.html.erb
<div class="container">
	<h4> Online demos are conducted every XXXX day of every month.  Please schedule your demo below</h4>
	<div class="col-md-4" >
	   
	   <input id="picker_simple" class="datepicker" type="text" readonly="">
	   
	</div> 
</div>

<script> $('.datepicker').pickadate(
	{
    format: 'You selected: dddd, dd mmm, yyyy',
    formatSubmit: 'yyyy/mm/dd'});
</script>

app/views/pages/features.html.erb
	    <ul class="nav nav-pills nav-justified">      
	      <li><a href="#ring">Ring Up <br>Sales</a></li>
	      <li><a href="#manage">Manage Your <br> Business</a></li>
	      <li><a href="#grow">Market and <br> Grow</a></li>
	      <li><a href="#support">7-day <br>Live Support</a></li>
	    </ul>
  



<div class="container-fluid features-top">
	<div class="row">
		<div class="col-md-12 col-centered text-center">
		<h3>Know Grow Save</h3>
		<h4>A full suite of products packed into one solution</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-md-offset-1  col-centered">
		<%= image_tag 'full-package.jpg' %>
		</div>
	</div><!--end row-->
	<div class="row">
	<div class="container feautre-list">
		<div class="col-md-5 text-right">
			<table>
			<th class="text-right"> Inventory Management</th>
			<tr><td>Know which itms are your best sellers to keep them in stock</td><tr>
			<th class="text-right">Multi-Store Management</th>
			<tr><td>Managing multiple locations dosen't have to be so complicated</td></tr>
			<th class="text-right">Consolidated Reporting</th>
			<tr><td>Track sales and cash-for all locations-form anywhere</td></tr>
			</table>
		</div>	
		<div class="col-md-1 text-left">
			<table>
			<tr><td><span class="glyphicon glyphicon-check feature-list-icon-lf"></span></td></tr>
			<tr><td><span class="glyphicon glyphicon-tags feature-list-icon"></span></td></tr>
			<tr><td><span class="glyphicon glyphicon-tasks feature-list-icon"></span></td></tr>
			</table>
		</div>
		<div class="col-md-1">
			<table>
			<tr><td><span class="glyphicon glyphicon-lock feature-list-icon"></span></td></tr>
			<tr><td><span class="glyphicon glyphicon-calendar feature-list-icon"></span></td></tr>
			<tr><td><span class="glyphicon glyphicon-phone-alt feature-list-icon"></span></td></tr>
			</table>
		</div>
		<div class="col-md-5text-left text-left">
			<table>
			<th> Advanced Security</th>
			<tr><td>Get fraud alerts and end-to-end payment encryption</td><tr>
			<th>Employee Management</th>
			<tr><td>Assign roles and track employee time with clock-in/clock-out/td></tr>
			<th>Live Support 7 Days a Week</th>
			<tr><td>We're here 24/7</td></tr>
			</table>
		</div>
	</div> <!--end feature list container-->	
</div><!--end features top container-->

<div class="container-fluid features-row" id="ring">
	<div class="row">
		<div class="col-md-4 col-md-offset-1">
			<h3>Ring Up Sales</h3>
				<ul>
					<li>Cloud-based Register App</li>
					<li>Quick charge function</li>
					<li>Payment Processing</li>
					<li>Change line item quantity</li>
					<li>Apply discounts</li>
					<li>Override pricing</li>

				</ul>
		</div>
		<div class="col-md-6">
			<div class="container">
				<iframe  class="features-video" src="//www.youtube.com/embed/4SvrtseaZHM?list=PL-js2VJiZHzmmCVyh9tlpmv8lZOpaxy24" frameborder="0" allowfullscreen></iframe>
			</div>
		</div>
	</div><!--end row-->
</div><!--end features ring container-->

<div class="container-fluid features-row" id="manage">
	<div class="row">
		<div class="col-md-4 col-md-offset-1">
			<div class="container">
				<iframe class="features-video"  src="//www.youtube.com/embed/LOQQasSKlC4?list=PL-js2VJiZHzmmCVyh9tlpmv8lZOpaxy24" frameborder="0" allowfullscreen></iframe>
			</div>
		</div>
		<div class="col-md-6">
			<h3>Manage Your Business</h3>
				<ul>
					<li>Sales Trends</li>
					<li>Profitability</li>
					<li>Top/Bottom Items</li>
					<li>Tax report</li>
					<li>Cash Management</li>
					<li>Data Exports</li>

				</ul>
		</div>
		
	</div><!--end row-->
</div><!--end features manage container-->

<div class="container-fluid features-row" id="grow">
	<div class="row">
		<div class="col-md-4 col-md-offset-1">
			<h3>Grow Your Business with Customer Marketing</h3>
				<ul>
					<li>Completely Integrated</li>
					<li>Target Offers/Messages</li>
					<li>Built in Campaigns</li>
					<li>Customizable Loyalty Programs</li>
					<li>Social Media Integration</li>
					<li>Coupons on Receipts</li>

				</ul>
		</div>
		<div class="col-md-6">
			<div class="container">
				<iframe class="features-video"  src="//www.youtube.com/embed/eKwOZm-iHQ8?list=PL-js2VJiZHzmmCVyh9tlpmv8lZOpaxy24" frameborder="0" allowfullscreen></iframe>
			</div>
		</div>
	</div><!--end row-->
</div><!--end features grow container-->

<div class="container-fluid features-row" id="support">
	<div class="row">
		<div class="col-md-4 col-md-offset-1">
			<div class="container support">
				<%= image_tag 'support.jpg' %>
			</div>
		</div>
		<div class="col-md-6">
			<h3>Support When You Need It</h3>
				<ul>
					<li>Technical issues and questions</li>
					<li>Using the App and Back Office</li>
					<li>How to get the most out of Vantiv Mobile Checkout</li>
					<li>US-based call center, skill set training</li>
					<li>Live support available 7 days a week</li>
				</ul>
			<h3>Need a little more assistance?</h3>

			<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#conciergeModal"> Checkout our Concierge Set-up Service</button>

<!-- Modal -->
				<div class="modal fade" id="conciergeModal" tabindex="-1" role="dialog" aria-labelledby="conciergeModalLabel" aria-hidden="true">
  					<div class="modal-dialog">
    					<div class="modal-content">
      						<div class="modal-header">
        						<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
       								 <h4 class="modal-title" id="conciergeModalLabel">Concierge Set-up Service</h4>
      						</div>
     						 <div class="modal-body">
       							<%= image_tag 'concierge.jpg' %>
      						</div>
     						<div class="modal-footer">
        						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
      						</div>
   						 </div>
  					</div>
				</div>
			
			</div>

	</div><!--end row-->
</div><!--end features support container-->

app/views/pages/get_started.html.erb
<div class ="container get_started">
	<div class ="row">
		<div class ="col-md-6">
			<h1>Congratulations!</h1>
				<p>You'll receive a call shortly from one of our account executives to help you get started.  In the meantime you can download the app and take it for a test drive. <%= link_to 'Download now', 'https://itunes.apple.com/us/app/vantiv-mobile-checkout/id644331179?mt=8' %>
				</p>
					<span id="download_app"> <%= link_to image_tag('vmc_app.png'), 'https://itunes.apple.com/us/app/vantiv-mobile-checkout/id644331179?mt=8' %>
					</span>
		</div>
		<div class ="col-md-6">
			 <%=  image_tag 'VMCbasicsetup.png' %>
		</div>
	</div>

</div>

app/views/pages/pricing.html.erb
<div class="container pricing-top">
	<div class="row">
		<div class= "col-md-6">
			<h1> Vantiv Mobile Checkout</h1>
			<h3> Ready to Go Out of the Box </h3>
			<button type="button" class="btn btn-blue">Get Started</button> 
			<button type="button" class="btn btn-blue">Watch Video</button>
		</div>
		<div class="container pricing-top col-md-6">
			 <%= image_tag 'VMCbasicsetup.png' %>
		</div>
	</div> 
</div>

<hr>

<div class="container pricing-mid">
	<div class="row">
		<div class="col-md-6">
			<div class="col-md-12 price">
				<h2> Equipment Purchase Options </h2>
				<div class="col-md-6 bluebox">
					Purchase for <h3>$499</h3>
				</div>
				<div class="col-md-6 bluebox">
					or lease for <h3> $40/mo</h3>
				</div>
			</div>
				<div class="col-md-12">
					<h4>Vantiv Mobile Checkout station includes:</h4>
					<div class= "col-md-8">
						
						<ul>
							<li>Countertop Receipt Printer </li>
							<li>Ethernet Wire </li>
							<li> Drawer with insert </li>
							<li>Tablet Stand </li>
							<li>Encrypted Card Reader with Charging Cable </li>
							<li>Printer Roll</li>
						</ul>
					</div>
					<div class= "col-md-4 equipment"> 
						 <%= image_tag 'VMCbasicsetup.png' %>
					</div>
				</div>
				<div class="col-md-12">
					<h4>Additional Equipment</h4>
					<div class= "col-md-4">
						
						<ul style="list-style-type: none;">
							<li>Kitchen Printer </li>
							<li>Barcode Scaner </li>
							<li>Mobile Receipt Printer </li>
						</ul>
					</div>
					<div class= "col-md-8"> 
						<ul style="list-style-type: none;">
							<li>$299 purchase /$19 36-month lease</li>
							<li>$299 purchase /$19 36-month lease</li>
							<li>$399 purchase /$23 36-month lease</li>
						</ul>
					</div>
				</div>

			<div class="col-md-12 price">
				<h2> Service Fees </h2>
				<div class="col-md-6 bluebox">
					First Stateion <h3>$59/mo</h3>
				</div>
				<div class="col-md-6 bluebox">
					Each Additional Station <h3> $29/mo</h3>
				</div>
				Includes 24/7 technical support and 100% US based customer service.
				<br><br>
				<button type="submit" class="btn btn-blue" style="position:center;">Get Started</button>

			</div>

		</div> <!--close left column -->
		<br>
		<div class="col-md-6">
			<div class="container processing_fees">
				<h2>Merchant Processing Rates and Fees:</h2>
				<p>Our pricing fees are very straight forward.  To keep costs down for our merchants, the fees are lowered as your processing volume increases. </p>

				<table class="table">
					<th> Visa&reg; / Mastercard&reg; / Discover&reg; Discount Rates </th>
					<tbody>
						<th> 
							<tr>
								<td><h4>Your Monthly Sales</h4></td>  <td><h4>Swiped Transactions*</h4></td>
								</h4>
							</tr>
						</th>
						<tr>
							<td>$0.00 - $4,999.99</td> <td>2.50% + $0.20 </td>
						</tr>
						<tr>
							<td>$5,000.00 - $9,999.99</td> <td>2.30% + $0.20 </td>
						</tr>
						<tr>
							<td>$10,000.00 - $24,999.999</td> <td>2.05% + $0.20 </td>
						</tr>
						<tr>
							<td>$25,000.00 or greater</td> <td>1.89% + $0.20 </td>
						</tr>

					</tbody>


				</table>
				<table class="table small_text">
					<tbody>
						<p class="small_text">
						*An additional rate of 1.1% will be applied to non-swiped monthly dollar volume.
						</p>
						<p>
						<strong>American Express&reg; OnePoint Rates and Fees</strong><br>
						<p class="small_text">For American Express rates range from 2.30% - 3.50% + $0.00 - $0.15 and will vary based a variety of factors. Please review your merchant agreement which will contain the rate you will be charged.
						</p>
						<p class="small_text">
						Additional 0.40% applies to cards issued outside of the U.S. Retail, Restaurant, Travel Agencies and Tour Operators will be charged an additional 0.30% on keyed / non-swiped / non-qualified American Express transactions. 
						</p>
						<p class="small_text">
						*Other rates and fees may apply and will vary based on a variety of factors. Please review your merchant agreement and statements for more information.
						</p>
					<tbody>
				</table>

			</div>
		</div> <!--close right column -->
	</div> <!--close row -->
	
</div> <!--close container-->

app/views/pages/shop.html.erb
<div class="container shop">
	<div class="row">
		<div class="col-md-8">
		<h4>Shop Shop Shop</h4>
			<table class="table">
			      	<tr>
				      	<th>Name</th>
				      	<th>Price</th>
				      	<th>Image</th>
				      	<th>Purchase</th>
				    </tr>  
		      	
		 	 
		 	 	<tbody>
		 	 	<% @products.each do |product| %>
			    	<tr>
				        <td><%= link_to product.name, product %></td>
				        <td><%= product.amount %></td>
				        <td class="shop"><%= image_tag (product.image_url) %></td>
				       
				        <td> <%= render partial: "shared/stripe_checkout_button", locals: {product: product} %> </td>
		       				
			    	</tr>
		   			 <%end%>
		      
		      </tbody>
		   	</table>
		   
   		</div>
   		<div class="col-md-4">
   			<h4> something to be refreshed here</h4>
   		</div>
   	</div>
</div>

app/views/products/edit.html.erb
<div class="container">

	<h1>Editing product</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Cost</th>
      <th>Manufacture part</th>
      <th>TMS ID</th>
      <th>Quick overview</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.amount %></td>
        <td><%= product.cost %></td>
        <td><%= product.manufacture_part %></td>
        <td><%= product.tms_id %></td>
        <td><%= product.quick_overview %></td>
        <td class="shop"><%= image_tag (product.image_url) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-4 show">
       
        <%= image_tag (@product.image_url) %>
    
    </div>
    <div class="col-md-8">
      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @product.amount %>
      </p>
      <p>
        <strong>Cost:</strong>
        <%= @product.cost %>
      </p>

      <p>
        <strong>Manufacture part:</strong>
        <%= @product.manufacture_part %>
      </p>

      <p>
        <strong>TMS ID:</strong>
        <%= @product.tms_id %>
      </p>

      <p>
        <strong>Quick overview:</strong>
        <%= @product.quick_overview %>
      </p>

      <p>
        <strong>Read more:</strong>
        <%= @product.read_more %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>
    </div>
  </div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', '/shop' %>

</div>

app/views/shared/_stripe_checkout_button.html.erb
<form action="/charge" method="POST">
	<script
	    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	    data-key= "<%= Rails.configuration.stripe[:publishable_key] %>"
	    data-image= "images/logosquare.png"
	    data-name="Tri-State Merchant"
	    data-description="<%= product.name %>"
	    data-amount="<%= product.amount %>">
	  </script>
</form>

app/views/users/edit.html.erb
<h4>edit.html.erb</h4>

app/views/users/show.html.erb
<h4>show.html.erb</h4>